### ISSUE TITLE
Is your project still alive ?

### ISSUE THREAD

**Issue by Gaspard-Bourgeois** [davidflam/OpenMoCap#1]
I wanted to know how far did you push your project ? Is it still working with the new OpenCV version ? Have you heard of any similar project ?

Thank you very much for this work, I find it really interesting.

**Comment by davidflam** [comment]
Hi Gaspard, 

we actually generated a few .BVH files and used them in very short animations. I haven't worked on it since the last commit here. OpenMoCap code was working with OpenCV 2.4.9, but this lib is now on version 4.3.0, therefore I guess it will not work (major versions almost always introduce breaking changes). As far as I know, project development is stopped. Haven't heard of a similar one, sorry.

Thanks for you message, I really appreciate it. Please feel to message me and/or contribute to this project.

Best,

David

**Comment by NavpreetDevpuri** [comment]
I don't know very much about how you achieved that motion capture but i think if we use following points it may be much better.
1. Make tracking for some kind of special cloths with tracking marks on it may be some lines and some points with different colors.
2. Use 2 or 4 cameras for taking videos from different sides of the body.

may be after that it can very much better for motion capture.

**Comment by NavpreetDevpuri** [comment]
May be we can implement that in python script in blender itself. 
just automate tracking points and tracking after that python can convert those values into motion captured data.
